require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/account/products", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Account::Product. As you add validations to Account::Product, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Account::Product.create! valid_attributes
      get account_products_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      product = Account::Product.create! valid_attributes
      get account_product_url(product)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_account_product_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      product = Account::Product.create! valid_attributes
      get edit_account_product_url(product)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Account::Product" do
        expect {
          post account_products_url, params: { account_product: valid_attributes }
        }.to change(Account::Product, :count).by(1)
      end

      it "redirects to the created account_product" do
        post account_products_url, params: { account_product: valid_attributes }
        expect(response).to redirect_to(account_product_url(Account::Product.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Account::Product" do
        expect {
          post account_products_url, params: { account_product: invalid_attributes }
        }.to change(Account::Product, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post account_products_url, params: { account_product: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested account_product" do
        product = Account::Product.create! valid_attributes
        patch account_product_url(product), params: { account_product: new_attributes }
        product.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the account_product" do
        product = Account::Product.create! valid_attributes
        patch account_product_url(product), params: { account_product: new_attributes }
        product.reload
        expect(response).to redirect_to(account_product_url(product))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        product = Account::Product.create! valid_attributes
        patch account_product_url(product), params: { account_product: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested account_product" do
      product = Account::Product.create! valid_attributes
      expect {
        delete account_product_url(product)
      }.to change(Account::Product, :count).by(-1)
    end

    it "redirects to the account_products list" do
      product = Account::Product.create! valid_attributes
      delete account_product_url(product)
      expect(response).to redirect_to(account_products_url)
    end
  end
end
